project_name: unarr

before:
  hooks:
    - go mod download

builds:
  - id: unarr-linux-x64
    binary: "{{ .ProjectName }}"
    # brew install FiloSottile/musl-cross/musl-cross
    main: ./cmd/unarr/unarr.go
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
    flags: &flags
      - "-trimpath"
    ldflags: &ldflags
      - "-s -w -extldflags '-static'"
    goos:
      - linux
    goarch:
      - amd64

  - id: unarr-linux-arm64
    binary: "{{ .ProjectName }}"
    main: ./cmd/unarr/unarr.go
    env:
      - CGO_ENABLED=1
      - CC=aarch64-pc-linux-musl-gcc
    flags: *flags
    ldflags: *ldflags
    goos:
      - linux
    goarch:
      - arm64

  - id: unarr-win-x64
    binary: "{{ .ProjectName }}"
    # brew install mingw-w64
    main: ./cmd/unarr/unarr.go
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    flags: *flags
    ldflags: *ldflags
    goos:
      - windows
    goarch:
      - amd64

  - id: unarr-darwin-x64
    binary: "{{ .ProjectName }}"
    main: ./cmd/unarr/unarr.go
    env:
      - CGO_ENABLED=1
      - CC=x86_64-apple-darwin21.4-clang
    flags: *flags
    ldflags:
      - "-s -w"
    goos:
      - darwin
    goarch:
      - amd64

  - id: unarr-darwin-arm64
    binary: "{{ .ProjectName }}"
    main: ./cmd/unarr/unarr.go
    env:
      - CGO_ENABLED=1
      - CC=aarch64-apple-darwin21.4-clang
    flags: *flags
    ldflags:
      - "-s -w"
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - id: archive
    wrap_in_directory: "{{ .ProjectName }}-{{ .Version }}"
    name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
